Added sdoc generation script for all ruby projects, and added as scheduled task.

diff --git a/bin/bundle_check_or_install b/bin/bundle_check_or_install
--- a/bin/bundle_check_or_install
+++ b/bin/bundle_check_or_install
@@ -1,4 +1,4 @@
-#!/bin/bash -l
+#!/bin/bash
 # Checks for Gemfile, and installs bundle if there are any unsatisfied gem dependens
 # ----------------------------------------------------------------------------------
 source "$DOTFILES_PATH/_shared_bin/functions.sh"
@@ -6,21 +6,22 @@ REVISION_FILE=".bundle_auto_install_revision~"
 
 abort_if_revision_unchanged "$REVISION_FILE"
 
-if [ -e Gemfile ]; then
-  rvmrc_or_default
-  ensure_gem bundler
+# Project must contain a Gemfile
+if ! [ -e Gemfile ]; then exit; fi
 
-  echo "== in: $PWD"
-  if ! bundle check; then
-    if bundle install; then
-      notify-send "Bundle installed" "Updated gems for $(basename $PWD) ($(parse_ruby_version))"
-    else
-      notify-send "Bundle failed" "Could not update gem dependencies for $(basename $PWD) ($(parse_ruby_version))"
-      # Create a flag so that we don't keep retrying failed bundle installs
-      git_exclude "$SKIP_FILE"
-      touch "$SKIP_FILE"
-    fi
+rvmrc_or_default
+ensure_gem bundler
+
+echo "== in: $PWD"
+if ! bundle check; then
+  if bundle install; then
+    notify-send "Bundle installed" "Updated gems for $(basename $PWD) ($(parse_ruby_version))"
+  else
+    notify-send "Bundle failed" "Could not update gem dependencies for $(basename $PWD) ($(parse_ruby_version))"
+    # Create a flag so that we don't keep retrying failed bundle installs
+    git_exclude "$SKIP_FILE"
+    touch "$SKIP_FILE"
   fi
-
-  store_current_revision "$REVISION_FILE"
 fi
+
+store_current_revision "$REVISION_FILE"
