added NO_COLOR option to color_index script. Used bash 3 boilerplate

diff --git a/bin/color_index b/bin/color_index
--- a/bin/color_index
+++ b/bin/color_index
@@ -1,18 +1,37 @@
 #!/usr/bin/env bash
 
+# shellcheck disable=SC2015
+[[ "${__helptext+x}" ]] || read -r -d '' __helptext <<-'EOF' || true # exits non-zero when EOF encountered
+ Prints out an index of all the available colors in the terminal.
+EOF
+
+source "$(dirname "${BASH_SOURCE[0]}")/../lib/b3bp.sh"
 
 # Bash Colors Index
 # Shows an index of all available bash colors
 # ------------------------------------------------
-echo -e "\n              Usage: \\\033[*;**(;**)m"
-echo -e   "            Default: \\\033[0m"
-blank_line="\033[0m\n     \033[0;30;40m$(printf "%41s")\033[0m"
+echo -e "\n     Usage:   \\\033[*;**(;**)m"
+echo -e   "     Default: \\\033[0m"
+
+if [[ $NO_COLOR == "true" ]]; then
+  echo -e "     (NO_COLOR is set to true, so no colors will be shown.)"
+  FG_COLORS="37"
+  BG_COLORS="47"
+  blank_line="\033[0m\n     \033[0;30;40m$(printf "%11s")\033[0m"
+else
+  FG_COLORS="$(seq 31 37)"
+  BG_COLORS="$(seq 41 47)"
+  blank_line="\033[0m\n     \033[0;30;40m$(printf "%41s")\033[0m"
+fi
+
 echo -e "$blank_line" # Top border
+
 for style in 2 0 1 4 9; do
   echo -en "     \033[0;30;40m "
   # Display black fg on white bg
   echo -en "\033[${style};30;47m${style};30\033[0;30;40m "
-  for foreground in $(seq 31 37); do
+
+  for foreground in $FG_COLORS; do
       ctrl="\033[${style};${foreground};40m"
       echo -en "${ctrl}"
       echo -en "${style};${foreground}\033[0;30;40m "
@@ -22,7 +41,7 @@ done
 echo -en "     \033[0;30;40m "
 # Background colors
 echo -en "\033[0;37;40m*;40\033[0;30;40m \033[0m" # Display white fg on black bg
-for background in $(seq 41 47); do
+for background in $BG_COLORS; do
     ctrl="\033[0;30;${background}m"
     echo -en "${ctrl}"
     echo -en "*;${background}\033[0;30;40m "
