Fixes for latest run

diff --git a/bin/dropbox_backup b/bin/dropbox_backup
--- a/bin/dropbox_backup
+++ b/bin/dropbox_backup
@@ -1,8 +1,10 @@
 #!/usr/bin/env bash
 set -eo pipefail
 
-if ! [ -d "$HOME/Dropbox" ]; then
-  echo "Could not find Dropbox folder at $HOME/Dropbox. Please set up Dropbox first."
+DROPBOX_DIR="$HOME/Library/CloudStorage/Dropbox"
+
+if ! [ -d "$DROPBOX_DIR" ]; then
+  echo "Could not find Dropbox folder at $DROPBOX_DIR. Please set up Dropbox first."
   exit 1
 fi
 
@@ -25,7 +27,7 @@ if [ -z "$1" ]; then
   exit 1
 fi
 
-DROPBOX_FOLDER="$HOME/Dropbox/Config"
+DROPBOX_FOLDER="$DROPBOX_DIR/Config"
 
 function save_files() {
   mkdir -p "$DROPBOX_FOLDER"
@@ -35,7 +37,7 @@ function save_files() {
   ENCRYPTED_FILES_PATH="$DROPBOX_FOLDER/$CONFIG_DIR.tar.gz.encrypted"
   echo "=> Encrypting $CONFIG_PATH and saving to ${ENCRYPTED_FILES_PATH}..."
   cd "$CONFIG_PATH"
-  tar cz * | openssl enc -aes-256-cbc -e > "${ENCRYPTED_FILES_PATH}"
+  tar cz * | openssl enc -aes-256-cbc -md md5 -e > "${ENCRYPTED_FILES_PATH}"
 }
 
 function restore_files() {
@@ -47,12 +49,12 @@ function restore_files() {
   fi
 
   echo "=> Decrypting and extracting ~/.$CONFIG_DIR from ${ENCRYPTED_FILES_PATH}..."
-  openssl aes-256-cbc -d -in "${ENCRYPTED_FILES_PATH}" -out /tmp/$CONFIG_DIR.tar.gz
+  openssl aes-256-cbc -d -md md5 -in "${ENCRYPTED_FILES_PATH}" -out /tmp/"$CONFIG_DIR".tar.gz
   rm -rf "$HOME/.$CONFIG_DIR"
   mkdir -p "$HOME/.$CONFIG_DIR"
   cd "$HOME/.$CONFIG_DIR"
-  tar xvf /tmp/$CONFIG_DIR.tar.gz
-  rm -rf /tmp/$CONFIG_DIR.tar.gz
+  tar xvf /tmp/"$CONFIG_DIR".tar.gz
+  rm -rf /tmp/"$CONFIG_DIR".tar.gz
 }
 
 function set_default_dirs() {
